-- ==============================================
-- JASPER E-COMMERCE SYSTEM - COMPLETE SCHEMA
-- ==============================================

-- ==============================================
-- 1. EXTENSIONS
-- ==============================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================
-- 2. TABLES
-- ==============================================

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: products
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    image_url TEXT,
    stock INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    weight_grams INTEGER DEFAULT 0, -- Pour calcul des frais de livraison
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: shipping_rates
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS shipping_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone TEXT NOT NULL, -- "france", "europe", "international"
    min_weight_grams INTEGER DEFAULT 0,
    max_weight_grams INTEGER,
    base_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    price_per_kg DECIMAL(10,2) DEFAULT 0.00,
    carrier TEXT NOT NULL DEFAULT 'cainiao', -- cainiao, la poste, etc.
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: promo_codes
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    discount_percent INTEGER NOT NULL DEFAULT 0,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_until TIMESTAMPTZ,
    max_uses INTEGER,
    times_used INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: orders
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    stripe_payment_intent_id TEXT,
    
    -- Montants
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    shipping_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(10,2) DEFAULT 0.00,
    tax_amount DECIMAL(10,2) DEFAULT 0.00,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    
    promo_code_id BIGINT REFERENCES promo_codes(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'pending', -- pending, paid, shipped, delivered, cancelled, refunded
    
    -- Adresse de livraison
    shipping_name TEXT NOT NULL,
    shipping_email TEXT NOT NULL,
    shipping_phone TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    shipping_city TEXT NOT NULL,
    shipping_postal_code TEXT NOT NULL,
    shipping_country TEXT NOT NULL,
    
    -- Dates importantes
    paid_at TIMESTAMPTZ,
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    refunded_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: order_items
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    product_name TEXT NOT NULL,
    product_price DECIMAL(10,2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: shipping_info
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS shipping_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    tracking_number TEXT,
    carrier TEXT,
    shipping_url TEXT,
    status TEXT DEFAULT 'preparing', -- preparing, shipped, in_transit, out_for_delivery, delivered
    estimated_delivery DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: fund_pool
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS fund_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status TEXT DEFAULT 'frozen', -- frozen, available, distributed
    frozen_until TIMESTAMPTZ NOT NULL, -- Date où les fonds deviennent disponibles (payement + 14 jours)
    released_at TIMESTAMPTZ,
    distributed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: dividend_distributions
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS dividend_distributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    total_amount DECIMAL(10,2) NOT NULL,
    admin1_share DECIMAL(10,2) NOT NULL,
    admin2_share DECIMAL(10,2) NOT NULL,
    admin1_stripe_transfer_id TEXT,
    admin2_stripe_transfer_id TEXT,
    status TEXT DEFAULT 'pending', -- pending, completed, failed
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: refunds
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    stripe_refund_id TEXT,
    amount DECIMAL(10,2) NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected, completed
    requested_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Table: profiles (pour étendre auth.users)
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    phone TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'customer', -- customer, admin
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================
-- 3. RLS POLICIES
-- ==============================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE fund_pool ENABLE ROW LEVEL SECURITY;
ALTER TABLE dividend_distributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: products (tout le monde peut lire)
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Products are viewable by everyone" 
    ON products FOR SELECT 
    USING (true);

CREATE POLICY "Only admins can manage products" 
    ON products FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: shipping_rates
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Shipping rates are viewable by everyone" 
    ON shipping_rates FOR SELECT 
    USING (true);

CREATE POLICY "Only admins can manage shipping rates" 
    ON shipping_rates FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: promo_codes
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Promo codes are viewable by everyone" 
    ON promo_codes FOR SELECT 
    USING (true);

CREATE POLICY "Only admins can manage promo codes" 
    ON promo_codes FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: orders
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Users can view their own orders" 
    ON orders FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own orders" 
    ON orders FOR INSERT 
    WITH CHECK (auth.uid() = user_id OR auth.uid() IS NULL);

CREATE POLICY "Admins can view and manage all orders" 
    ON orders FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: order_items
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Order items are viewable by their order owner or admins" 
    ON order_items FOR SELECT 
    USING (
        EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
        OR 
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
    );

CREATE POLICY "Order items can be created by anyone" 
    ON order_items FOR INSERT 
    WITH CHECK (true);

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: shipping_info
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Shipping info is viewable by their order owner or admins" 
    ON shipping_info FOR SELECT 
    USING (
        EXISTS (SELECT 1 FROM orders WHERE orders.id = shipping_info.order_id AND orders.user_id = auth.uid())
        OR 
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
    );

CREATE POLICY "Only admins can manage shipping info" 
    ON shipping_info FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: fund_pool (seulement admins)
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Only admins can view and manage fund pool" 
    ON fund_pool FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: dividend_distributions (seulement admins)
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Only admins can view and manage dividend distributions" 
    ON dividend_distributions FOR ALL 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: refunds
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Refunds are viewable by order owner or admins" 
    ON refunds FOR SELECT 
    USING (
        EXISTS (SELECT 1 FROM orders WHERE orders.id = refunds.order_id AND orders.user_id = auth.uid())
        OR 
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
    );

CREATE POLICY "Users can request refunds for their orders" 
    ON refunds FOR INSERT 
    WITH CHECK (
        EXISTS (SELECT 1 FROM orders WHERE orders.id = refunds.order_id AND orders.user_id = auth.uid())
    );

CREATE POLICY "Only admins can manage refunds" 
    ON refunds FOR UPDATE 
    USING (auth.role() = 'authenticated' AND (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    ));

-- --- --- --- --- --- --- --- --- --- --- --- 
-- Policies: profiles
-- --- --- --- --- --- --- --- --- --- --- --- 
CREATE POLICY "Users can view and edit their own profile" 
    ON profiles FOR SELECT 
    USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" 
    ON profiles FOR INSERT 
    WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
    ON profiles FOR UPDATE 
    USING (auth.uid() = id);

-- ==============================================
-- 4. AUTO-UPDATED TIMESTAMPS
-- ==============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_products_updated_at 
    BEFORE UPDATE ON products 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_shipping_rates_updated_at 
    BEFORE UPDATE ON shipping_rates 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_promo_codes_updated_at 
    BEFORE UPDATE ON promo_codes 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at 
    BEFORE UPDATE ON orders 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_shipping_info_updated_at 
    BEFORE UPDATE ON shipping_info 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_fund_pool_updated_at 
    BEFORE UPDATE ON fund_pool 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dividend_distributions_updated_at 
    BEFORE UPDATE ON dividend_distributions 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_refunds_updated_at 
    BEFORE UPDATE ON refunds 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_profiles_updated_at 
    BEFORE UPDATE ON profiles 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==============================================
-- 5. DEFAULT SHIPPING RATES (INITIAL DATA)
-- ==============================================
INSERT INTO shipping_rates (zone, min_weight_grams, max_weight_grams, base_price, price_per_kg, carrier, is_active)
VALUES
    ('france', 0, 1000, 4.99, 0.00, 'cainiao', TRUE),
    ('france', 1001, 3000, 6.99, 0.00, 'cainiao', TRUE),
    ('france', 3001, 10000, 9.99, 0.00, 'cainiao', TRUE),
    ('europe', 0, 2000, 14.99, 0.00, 'cainiao', TRUE),
    ('international', 0, 2000, 24.99, 0.00, 'cainiao', TRUE)
ON CONFLICT DO NOTHING;

-- ==============================================
-- 6. TRIGGER TO CREATE PROFILES ON USER SIGNUP
-- ==============================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, phone, role)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'phone', ''),
    'customer'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================
-- 7. FONCTION DE CALCUL DES FRAIS DE LIVRAISON
-- ==============================================
CREATE OR REPLACE FUNCTION calculate_shipping_cost(
    zone TEXT, 
    total_weight_grams INTEGER
) 
RETURNS DECIMAL(10,2) AS $$
DECLARE
    cost DECIMAL(10,2);
BEGIN
    SELECT 
        base_price + (GREATEST(0, (total_weight_grams / 1000.0 - 1)) * price_per_kg)
    INTO cost
    FROM shipping_rates
    WHERE 
        shipping_rates.zone = calculate_shipping_cost.zone
        AND shipping_rates.min_weight_grams <= total_weight_grams
        AND (shipping_rates.max_weight_grams IS NULL OR shipping_rates.max_weight_grams >= total_weight_grams)
        AND shipping_rates.is_active = TRUE
    ORDER BY shipping_rates.id ASC
    LIMIT 1;
    
    RETURN COALESCE(cost, 0.00);
END;
$$ LANGUAGE plpgsql;

-- ==============================================
-- 8. FONCTION POUR OBTENIR LE PRIX APRÈS PROMO
-- ==============================================
CREATE OR REPLACE FUNCTION apply_promo_code(
    promo_code_id BIGINT, 
    original_amount DECIMAL(10,2)
) 
RETURNS DECIMAL(10,2) AS $$
DECLARE
    discount_percent_val INTEGER;
    discount_amount_val DECIMAL(10,2);
BEGIN
    IF promo_code_id IS NULL THEN
        RETURN 0.00;
    END IF;
    
    SELECT discount_percent INTO discount_percent_val
    FROM promo_codes
    WHERE id = promo_code_id
        AND is_active = TRUE
        AND valid_from <= NOW()
        AND (valid_until IS NULL OR valid_until >= NOW())
        AND (max_uses IS NULL OR times_used < max_uses);
        
    IF discount_percent_val IS NULL THEN
        RETURN 0.00;
    END IF;
    
    discount_amount_val := original_amount * (discount_percent_val / 100.0);
    RETURN discount_amount_val;
END;
$$ LANGUAGE plpgsql;

-- ==============================================
-- 9. FONCTION POUR INCÉMENTER L'UTILISATION D'UN PROMO CODE
-- ==============================================
CREATE OR REPLACE FUNCTION increment_promo_code_usage(promo_id BIGINT)
RETURNS void AS $$
BEGIN
    UPDATE promo_codes 
    SET times_used = times_used + 1 
    WHERE id = promo_id;
END;
$$ LANGUAGE plpgsql;

-- ==============================================
-- FIN DE LA MIGRATION
-- ==============================================
