-- 修复和完善数据库 RLS 策略及缺失的功能

-- 1. 首先确保所有必要的表都存在
CREATE TYPE IF NOT EXISTS after_sales_status AS ENUM ('pending', 'in_review', 'resolved', 'cancelled');

-- 创建 Profile 表（如果不存在）
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'user',
    full_name TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    postal_code TEXT,
    country TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 创建售后表（如果不存在）
CREATE TABLE IF NOT EXISTS after_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    status after_sales_status DEFAULT 'pending',
    admin_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. 启用所有表的 RLS
ALTER TABLE IF EXISTS profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS after_sales ENABLE ROW LEVEL SECURITY;

-- 3. 创建或更新所有 RLS 策略

-- Profile 策略
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
CREATE POLICY "Users can view their own profile" 
    ON profiles FOR SELECT 
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
CREATE POLICY "Users can update their own profile" 
    ON profiles FOR UPDATE 
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
CREATE POLICY "Users can insert their own profile" 
    ON profiles FOR INSERT 
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Authenticated users can view all profiles" ON profiles;
CREATE POLICY "Authenticated users can view all profiles" 
    ON profiles FOR SELECT 
    USING (auth.role() = 'authenticated');

-- After-sales 策略
DROP POLICY IF EXISTS "Users can view their own after-sales" ON after_sales;
CREATE POLICY "Users can view their own after-sales" 
    ON after_sales FOR SELECT 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own after-sales" ON after_sales;
CREATE POLICY "Users can insert their own after-sales" 
    ON after_sales FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Authenticated users can manage after-sales" ON after_sales;
CREATE POLICY "Authenticated users can manage after-sales" 
    ON after_sales FOR ALL 
    USING (auth.role() = 'authenticated');

-- Orders 策略（完善）
DROP POLICY IF EXISTS "Users can view their own orders" ON orders;
CREATE POLICY "Users can view their own orders" 
    ON orders FOR SELECT 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can insert orders" ON orders;
CREATE POLICY "Anyone can insert orders" 
    ON orders FOR INSERT 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can view all orders" ON orders;
CREATE POLICY "Authenticated users can view all orders" 
    ON orders FOR SELECT 
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update orders" ON orders;
CREATE POLICY "Authenticated users can update orders" 
    ON orders FOR UPDATE 
    USING (auth.role() = 'authenticated');

-- Order Items 策略（完善）
DROP POLICY IF EXISTS "Users can view their own order items" ON order_items;
CREATE POLICY "Users can view their own order items" 
    ON order_items FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM orders 
            WHERE orders.id = order_items.order_id 
            AND (orders.user_id = auth.uid() OR auth.role() = 'authenticated')
        )
    );

DROP POLICY IF EXISTS "Anyone can insert order items" ON order_items;
CREATE POLICY "Anyone can insert order items" 
    ON order_items FOR INSERT 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can manage order items" ON order_items;
CREATE POLICY "Authenticated users can manage order items" 
    ON order_items FOR ALL 
    USING (auth.role() = 'authenticated');

-- Shipping Info 策略（完善）
DROP POLICY IF EXISTS "Users can view their own shipping info" ON shipping_info;
CREATE POLICY "Users can view their own shipping info" 
    ON shipping_info FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM orders 
            WHERE orders.id = shipping_info.order_id 
            AND (orders.user_id = auth.uid() OR auth.role() = 'authenticated')
        )
    );

DROP POLICY IF EXISTS "Anyone can insert shipping info" ON shipping_info;
CREATE POLICY "Anyone can insert shipping info" 
    ON shipping_info FOR INSERT 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can manage shipping info" ON shipping_info;
CREATE POLICY "Authenticated users can manage shipping info" 
    ON shipping_info FOR ALL 
    USING (auth.role() = 'authenticated');

-- Stripe Transfers 策略
DROP POLICY IF EXISTS "Only authenticated can view transfers" ON stripe_transfers;
CREATE POLICY "Only authenticated can view transfers" 
    ON stripe_transfers FOR SELECT 
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Only authenticated can insert transfers" ON stripe_transfers;
CREATE POLICY "Only authenticated can insert transfers" 
    ON stripe_transfers FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated');

-- 4. 创建或更新更新时间函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 5. 创建触发器
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at 
    BEFORE UPDATE ON profiles 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_after_sales_updated_at ON after_sales;
CREATE TRIGGER update_after_sales_updated_at 
    BEFORE UPDATE ON after_sales 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_stripe_transfers_updated_at ON stripe_transfers;
CREATE TRIGGER update_stripe_transfers_updated_at 
    BEFORE UPDATE ON stripe_transfers 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;
CREATE TRIGGER update_orders_updated_at 
    BEFORE UPDATE ON orders 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_promo_codes_updated_at ON promo_codes;
CREATE TRIGGER update_promo_codes_updated_at 
    BEFORE UPDATE ON promo_codes 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at 
    BEFORE UPDATE ON products 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_shipping_info_updated_at ON shipping_info;
CREATE TRIGGER update_shipping_info_updated_at 
    BEFORE UPDATE ON shipping_info 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 6. 创建或更新自动创建 Profile 的触发器函数
DROP FUNCTION IF EXISTS public.handle_new_user CASCADE;
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (id, role, full_name)
    VALUES (
        NEW.id, 
        'user', 
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', NEW.email)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. 创建用户注册触发器
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 8. 创建增加优惠码使用次数的函数
CREATE OR REPLACE FUNCTION increment_promo_code_usage(code_id BIGINT)
RETURNS VOID AS $$
BEGIN
    UPDATE promo_codes 
    SET times_used = times_used + 1
    WHERE id = code_id;
END;
$$ LANGUAGE plpgsql;
