-- 添加 Newsletter 和 Contact 管理功能的数据库迁移

-- 1. 创建 Newsletter 订阅表
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    subscribed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. 创建 Newsletter 消息表（用于群发）
CREATE TABLE IF NOT EXISTS newsletter_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    sent_at TIMESTAMPTZ,
    is_draft BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. 创建 Contact/SAV 消息表（合并 SAV 和 Contact）
CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'general', -- 'general' or 'sav'
    status TEXT DEFAULT 'new', -- 'new', 'in_progress', 'resolved'
    admin_notes TEXT,
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. 启用 RLS
ALTER TABLE IF EXISTS newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS newsletter_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contact_messages ENABLE ROW LEVEL SECURITY;

-- 5. RLS 策略

-- Newsletter Subscribers 策略
DROP POLICY IF EXISTS "Anyone can subscribe to newsletter" ON newsletter_subscribers;
CREATE POLICY "Anyone can subscribe to newsletter" 
    ON newsletter_subscribers FOR INSERT 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can view all subscribers" ON newsletter_subscribers;
CREATE POLICY "Authenticated can view all subscribers" 
    ON newsletter_subscribers FOR SELECT 
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated can manage subscribers" ON newsletter_subscribers;
CREATE POLICY "Authenticated can manage subscribers" 
    ON newsletter_subscribers FOR ALL 
    USING (auth.role() = 'authenticated');

-- Newsletter Messages 策略
DROP POLICY IF EXISTS "Authenticated can view all messages" ON newsletter_messages;
CREATE POLICY "Authenticated can view all messages" 
    ON newsletter_messages FOR SELECT 
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated can manage messages" ON newsletter_messages;
CREATE POLICY "Authenticated can manage messages" 
    ON newsletter_messages FOR ALL 
    USING (auth.role() = 'authenticated');

-- Contact Messages 策略
DROP POLICY IF EXISTS "Anyone can send contact message" ON contact_messages;
CREATE POLICY "Anyone can send contact message" 
    ON contact_messages FOR INSERT 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can view all contact messages" ON contact_messages;
CREATE POLICY "Authenticated can view all contact messages" 
    ON contact_messages FOR SELECT 
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated can manage contact messages" ON contact_messages;
CREATE POLICY "Authenticated can manage contact messages" 
    ON contact_messages FOR ALL 
    USING (auth.role() = 'authenticated');

-- 6. 更新时间触发器
DROP TRIGGER IF EXISTS update_newsletter_subscribers_updated_at ON newsletter_subscribers;
CREATE TRIGGER update_newsletter_subscribers_updated_at 
    BEFORE UPDATE ON newsletter_subscribers 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_newsletter_messages_updated_at ON newsletter_messages;
CREATE TRIGGER update_newsletter_messages_updated_at 
    BEFORE UPDATE ON newsletter_messages 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_contact_messages_updated_at ON contact_messages;
CREATE TRIGGER update_contact_messages_updated_at 
    BEFORE UPDATE ON contact_messages 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
